name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Change ici si ton site est sur une autre branche

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}  # Assure-toi que c'est bien référencé comme ça
          password: ${{ secrets.FTP_PASSWORD }}  # Pareil pour le mot de passe
          local-dir: ./
          server-dir: /tominou.tech/htdocs/
